extends Node
class_name BQCityLife

## Procedural civilian and traffic layer for Landly City.
## Background characters are generated by the game; main heroes remain separate.

const ROLES := ["CITIZEN", "STUDENT", "WORKER", "OFFICER", "COMMUTER", "SHOPPER"]
const CLOTHES := [
    Color(0.08, 0.11, 0.16), Color(0.12, 0.24, 0.34), Color(0.22, 0.16, 0.20),
    Color(0.18, 0.20, 0.23), Color(0.30, 0.20, 0.12), Color(0.10, 0.28, 0.24)
]
const SKIN_TONES := [
    Color(0.22, 0.13, 0.09), Color(0.34, 0.21, 0.14), Color(0.45, 0.30, 0.20),
    Color(0.56, 0.38, 0.25), Color(0.29, 0.17, 0.11)
]

var population_root: Node3D
var rng := RandomNumberGenerator.new()
var walkers: Array[Node3D] = []
var traffic: Array[Node3D] = []

func build(parent: Node3D) -> void:
    population_root = Node3D.new()
    population_root.name = "LandlyCityPopulation"
    parent.add_child(population_root)
    rng.seed = 420826
    _build_citizens()
    _build_traffic()
    _build_service_zones()

func _process(delta: float) -> void:
    for person in walkers:
        if not is_instance_valid(person):
            continue
        var progress := float(person.get_meta("walk_progress", 0.0))
        var speed := float(person.get_meta("walk_speed", 0.65))
        var a: Vector3 = person.get_meta("walk_a", person.position)
        var b: Vector3 = person.get_meta("walk_b", person.position)
        progress = fmod(progress + delta * speed, 1.0)
        person.set_meta("walk_progress", progress)
        person.position = a.lerp(b, progress)
        var direction := b - a
        if direction.length_squared() > 0.01:
            person.rotation.y = atan2(direction.x, direction.z)

    for car in traffic:
        if not is_instance_valid(car):
            continue
        var progress := float(car.get_meta("traffic_progress", 0.0))
        var speed := float(car.get_meta("traffic_speed", 0.045))
        var a: Vector3 = car.get_meta("traffic_a", car.position)
        var b: Vector3 = car.get_meta("traffic_b", car.position)
        progress = fmod(progress + delta * speed, 1.0)
        car.set_meta("traffic_progress", progress)
        car.position = a.lerp(b, progress)
        var direction := b - a
        if direction.length_squared() > 0.01:
            car.rotation.y = atan2(direction.x, direction.z)

func _build_citizens() -> void:
    var spawn_points := [
        Vector3(-24, 0.0, -8), Vector3(-16, 0.0, 8), Vector3(18, 0.0, -8), Vector3(26, 0.0, 10),
        Vector3(-34, 0.0, 18), Vector3(34, 0.0, -18), Vector3(-12, 0.0, 34), Vector3(12, 0.0, 34),
        Vector3(-44, 0.0, -12), Vector3(44, 0.0, 12), Vector3(-30, 0.0, -38), Vector3(30, 0.0, -38),
        Vector3(-2, 0.0, 24), Vector3(2, 0.0, -24), Vector3(-52, 0.0, 20), Vector3(52, 0.0, -20),
        Vector3(-58, 0.0, -34), Vector3(-50, 0.0, -40), Vector3(-42, 0.0, -34), Vector3(42, 0.0, -34),
        Vector3(50, 0.0, -40), Vector3(58, 0.0, -34), Vector3(-50, 0.0, 38), Vector3(50, 0.0, 38),
        Vector3(-34, 0.0, 48), Vector3(34, 0.0, 48), Vector3(-18, 0.0, 46), Vector3(18, 0.0, 46),
        Vector3(-46, 0.0, 8), Vector3(46, 0.0, -8)
    ]

    for i in range(spawn_points.size()):
        var start := spawn_points[i]
        var horizontal := i % 2 == 0
        var target := start + (Vector3(12, 0, 0) if horizontal else Vector3(0, 0, 12))
        if i % 4 == 1:
            target = start - (Vector3(12, 0, 0) if horizontal else Vector3(0, 0, 12))
        _add_person(start, target, ROLES[i % ROLES.size()], i)

func _add_person(start: Vector3, target: Vector3, role: String, index: int) -> void:
    var person := Node3D.new()
    person.name = "Civilian_%02d" % index
    person.position = start
    population_root.add_child(person)
    person.set_meta("walk_progress", float(index % 7) / 7.0)
    person.set_meta("walk_speed", 0.42 + float(index % 5) * 0.09)
    person.set_meta("walk_a", start)
    person.set_meta("walk_b", target)
    walkers.append(person)

    var outfit := CLOTHES[index % CLOTHES.size()]
    var skin := SKIN_TONES[(index * 3) % SKIN_TONES.size()]
    var scale := 0.88 + float(index % 4) * 0.06
    person.scale = Vector3.ONE * scale

    _capsule(person, Vector3(0, 1.05, 0), 0.34, 1.15, outfit, "Torso")
    _box(person, Vector3(0, 0.38, 0), Vector3(0.48, 0.22, 0.30), skin, "HandsBase")
    _sphere(person, Vector3(0, 1.85, 0), 0.24, skin, "Head")
    _sphere(person, Vector3(0, 2.03, 0), 0.245, Color(0.055, 0.045, 0.04), "Hair")

    var arm_color := outfit.lightened(0.08)
    _capsule(person, Vector3(-0.43, 1.1, 0), 0.105, 0.82, arm_color, "ArmL")
    _capsule(person, Vector3(0.43, 1.1, 0), 0.105, 0.82, arm_color, "ArmR")
    _capsule(person, Vector3(-0.16, 0.35, 0), 0.12, 0.76, Color(0.07, 0.08, 0.10), "LegL")
    _capsule(person, Vector3(0.16, 0.35, 0), 0.12, 0.76, Color(0.07, 0.08, 0.10), "LegR")

    if role == "STUDENT":
        _box(person, Vector3(0, 1.08, -0.34), Vector3(0.44, 0.45, 0.08), Color(0.10, 0.16, 0.24), "Backpack")
    elif role == "OFFICER":
        _box(person, Vector3(0, 1.35, -0.30), Vector3(0.34, 0.10, 0.05), Color(0.65, 0.72, 0.78), "Badge")

func _build_traffic() -> void:
    var traffic_root := Node3D.new()
    traffic_root.name = "LandlyTraffic"
    population_root.add_child(traffic_root)

    var routes := [
        [Vector3(-58, 0.48, 3.0), Vector3(58, 0.48, 3.0)],
        [Vector3(58, 0.48, -3.0), Vector3(-58, 0.48, -3.0)],
        [Vector3(-3.0, 0.48, -58), Vector3(-3.0, 0.48, 58)],
        [Vector3(3.0, 0.48, 58), Vector3(3.0, 0.48, -58)],
        [Vector3(-58, 0.48, 36), Vector3(58, 0.48, 36)]
    ]
    var colors := [Color(0.08, 0.18, 0.28), Color(0.22, 0.22, 0.25), Color(0.12, 0.30, 0.20), Color(0.32, 0.16, 0.12), Color(0.18, 0.18, 0.22)]

    for i in range(16):
        var route: Array = routes[i % routes.size()]
        var car := Node3D.new()
        car.name = "CityVehicle_%02d" % i
        car.position = route[0]
        traffic_root.add_child(car)
        car.set_meta("traffic_progress", float(i % 8) / 8.0)
        car.set_meta("traffic_speed", 0.032 + float(i % 4) * 0.006)
        car.set_meta("traffic_a", route[0])
        car.set_meta("traffic_b", route[1])
        traffic.append(car)

        _box(car, Vector3(0, 0.42, 0), Vector3(1.65, 0.62, 3.0), colors[i % colors.size()], "VehicleBody")
        _box(car, Vector3(0, 0.82, -0.15), Vector3(1.25, 0.38, 1.45), Color(0.08, 0.13, 0.18), "VehicleCabin")
        for x in [-0.68, 0.68]:
            for z in [-0.9, 0.9]:
                _cylinder(car, Vector3(x, 0.25, z), 0.16, 0.12, Color(0.035, 0.04, 0.05), "Wheel")
        _box(car, Vector3(0, 0.48, -1.53), Vector3(1.2, 0.08, 0.08), Color(0.65, 0.76, 0.82), "HeadLights")

func _build_service_zones() -> void:
    _add_sign(Vector3(-44, 3.2, -44), "LANDLY POLICE")
    _add_sign(Vector3(44, 3.2, -44), "LANDLY HOSPITAL")
    _add_sign(Vector3(-44, 3.2, 44), "LANDLY COLLEGE")
    _add_sign(Vector3(44, 3.2, 44), "DEFENCE ZONE")

func _add_sign(position: Vector3, title: String) -> void:
    var sign := Label3D.new()
    sign.text = title
    sign.font_size = 24
    sign.outline_size = 6
    sign.position = position
    sign.modulate = Color(0.55, 0.82, 1.0)
    sign.billboard = BaseMaterial3D.BILLBOARD_ENABLED
    population_root.add_child(sign)

func _capsule(parent: Node3D, position: Vector3, radius: float, height: float, color: Color, label: String) -> void:
    var mesh := MeshInstance3D.new()
    var shape := CapsuleMesh.new()
    shape.radius = radius
    shape.height = height
    mesh.mesh = shape
    mesh.position = position
    mesh.material_override = _material(color)
    mesh.name = label
    parent.add_child(mesh)

func _sphere(parent: Node3D, position: Vector3, radius: float, color: Color, label: String) -> void:
    var mesh := MeshInstance3D.new()
    var shape := SphereMesh.new()
    shape.radius = radius
    shape.height = radius * 2.0
    mesh.mesh = shape
    mesh.position = position
    mesh.material_override = _material(color)
    mesh.name = label
    parent.add_child(mesh)

func _cylinder(parent: Node3D, position: Vector3, radius: float, height: float, color: Color, label: String) -> void:
    var mesh := MeshInstance3D.new()
    var shape := CylinderMesh.new()
    shape.top_radius = radius
    shape.bottom_radius = radius
    shape.height = height
    mesh.mesh = shape
    mesh.position = position
    mesh.rotation.z = PI * 0.5
    mesh.material_override = _material(color)
    mesh.name = label
    parent.add_child(mesh)

func _box(parent: Node3D, position: Vector3, size: Vector3, color: Color, label: String) -> void:
    var mesh := MeshInstance3D.new()
    var shape := BoxMesh.new()
    shape.size = size
    mesh.mesh = shape
    mesh.position = position
    mesh.material_override = _material(color)
    mesh.name = label
    parent.add_child(mesh)

func _material(color: Color) -> StandardMaterial3D:
    var material := StandardMaterial3D.new()
    material.albedo_color = color
    material.roughness = 0.68
    return material
