extends Node
class_name BQCityLife

## Landly City population and traffic layer.
## Human citizens use NavigationAgent3D pathfinding with role-specific
## destinations and controlled avoidance. Visuals are procedural for now;
## imported human assets can replace the presentation without changing this
## population architecture.

const HUMAN_NPC := preload("res://scripts/landly_human_npc.gd")

const ROLE_SEQUENCE := [
    "CITIZEN", "STUDENT", "WORKER", "OFFICER", "COMMUTER", "SHOPPER",
    "TEACHER", "MEDICAL", "RESIDENT", "SERVICE"
]

const ROAD_Y := 0.24

var population_root: Node3D
var navigation_region_rid := RID()
var rng := RandomNumberGenerator.new()
var walkers: Array[Node3D] = []
var traffic: Array[Node3D] = []

func build(parent: Node3D) -> void:
    population_root = Node3D.new()
    population_root.name = "LandlyCityPopulation"
    parent.add_child(population_root)
    rng.seed = 420826

    _build_navigation(parent)
    _build_citizens()
    _build_traffic()
    _build_service_zones()

func _exit_tree() -> void:
    if navigation_region_rid.is_valid():
        NavigationServer3D.region_set_enabled(navigation_region_rid, false)
        NavigationServer3D.free_rid(navigation_region_rid)
        navigation_region_rid = RID()

func _build_navigation(parent: Node3D) -> void:
    # The city already has roads and sidewalks generated by main.gd. This
    # runtime mesh deliberately follows those public pedestrian corridors
    # instead of allowing NPCs to cut through buildings or the road center.
    var mesh := NavigationMesh.new()
    mesh.vertices = PackedVector3Array()

    _add_navigation_strip(mesh, Vector3(-58, ROAD_Y, -10), Vector3(58, ROAD_Y, -10), 3.0)
    _add_navigation_strip(mesh, Vector3(-58, ROAD_Y, 10), Vector3(58, ROAD_Y, 10), 3.0)
    _add_navigation_strip(mesh, Vector3(-58, ROAD_Y, -36), Vector3(58, ROAD_Y, -36), 2.6)
    _add_navigation_strip(mesh, Vector3(-58, ROAD_Y, 36), Vector3(58, ROAD_Y, 36), 2.6)
    _add_navigation_strip(mesh, Vector3(-10, ROAD_Y, -58), Vector3(-10, ROAD_Y, 58), 3.0)
    _add_navigation_strip(mesh, Vector3(10, ROAD_Y, -58), Vector3(10, ROAD_Y, 58), 3.0)
    _add_navigation_strip(mesh, Vector3(-36, ROAD_Y, -58), Vector3(-36, ROAD_Y, 58), 2.6)
    _add_navigation_strip(mesh, Vector3(36, ROAD_Y, -58), Vector3(36, ROAD_Y, 58), 2.6)

    navigation_region_rid = NavigationServer3D.region_create()
    NavigationServer3D.region_set_enabled(navigation_region_rid, true)
    NavigationServer3D.region_set_map(navigation_region_rid, parent.get_world_3d().get_navigation_map())
    NavigationServer3D.region_set_navigation_mesh(navigation_region_rid, mesh)

func _add_navigation_strip(mesh: NavigationMesh, a: Vector3, b: Vector3, half_width: float) -> void:
    var direction := (b - a).normalized()
    var side := Vector3(-direction.z, 0.0, direction.x) * half_width
    var base := mesh.vertices.size()
    mesh.vertices.append(a + side)
    mesh.vertices.append(b + side)
    mesh.vertices.append(b - side)
    mesh.vertices.append(a - side)
    mesh.add_polygon(PackedInt32Array([base, base + 1, base + 2, base + 3]))

func _build_citizens() -> void:
    var spawn_points := [
        Vector3(-24, ROAD_Y, -10), Vector3(-16, ROAD_Y, 10), Vector3(18, ROAD_Y, -10), Vector3(26, ROAD_Y, 10),
        Vector3(-36, ROAD_Y, 18), Vector3(36, ROAD_Y, -18), Vector3(-10, ROAD_Y, 34), Vector3(10, ROAD_Y, 34),
        Vector3(-36, ROAD_Y, -18), Vector3(36, ROAD_Y, 18), Vector3(-10, ROAD_Y, -34), Vector3(10, ROAD_Y, -34),
        Vector3(-36, ROAD_Y, 42), Vector3(36, ROAD_Y, 42), Vector3(-42, ROAD_Y, -36), Vector3(42, ROAD_Y, -36),
        Vector3(-36, ROAD_Y, -42), Vector3(36, ROAD_Y, -42), Vector3(-42, ROAD_Y, 36), Vector3(42, ROAD_Y, 36),
        Vector3(-10, ROAD_Y, 46), Vector3(10, ROAD_Y, 46), Vector3(-10, ROAD_Y, -46), Vector3(10, ROAD_Y, -46),
        Vector3(-46, ROAD_Y, -10), Vector3(-46, ROAD_Y, 10), Vector3(46, ROAD_Y, -10), Vector3(46, ROAD_Y, 10),
        Vector3(-36, ROAD_Y, 10), Vector3(36, ROAD_Y, -10), Vector3(-10, ROAD_Y, 36), Vector3(10, ROAD_Y, -36),
        Vector3(-36, ROAD_Y, -10), Vector3(36, ROAD_Y, 10), Vector3(-10, ROAD_Y, -36), Vector3(10, ROAD_Y, 36)
    ]

    for i in range(spawn_points.size()):
        _add_human(spawn_points[i], i)

func _add_human(start: Vector3, index: int) -> void:
    var person := CharacterBody3D.new()
    person.name = "LandlyHuman_%03d" % index
    person.position = start
    person.set_script(HUMAN_NPC)
    person.set_meta("npc_role", ROLE_SEQUENCE[index % ROLE_SEQUENCE.size()])
    person.set_meta("npc_variant", index)
    person.set_meta("npc_speed", 1.15 + float(index % 6) * 0.13)
    # Keep avoidance enabled for a bounded subset of citizens. Distant agents
    # still pathfind normally, reducing Android CPU cost.
    person.set_meta("npc_avoidance", index < 14)
    person.set_meta("npc_destinations", _destinations_for_role(ROLE_SEQUENCE[index % ROLE_SEQUENCE.size()]))
    population_root.add_child(person)
    walkers.append(person)

func _destinations_for_role(role: String) -> Array[Vector3]:
    match role:
        "STUDENT", "TEACHER":
            return [
                Vector3(-36, ROAD_Y, 36), Vector3(-36, ROAD_Y, 42),
                Vector3(-10, ROAD_Y, 36), Vector3(10, ROAD_Y, 36)
            ]
        "MEDICAL":
            return [
                Vector3(36, ROAD_Y, -36), Vector3(36, ROAD_Y, -42),
                Vector3(10, ROAD_Y, -36), Vector3(36, ROAD_Y, -10)
            ]
        "OFFICER":
            return [
                Vector3(-36, ROAD_Y, -36), Vector3(-36, ROAD_Y, -42),
                Vector3(-10, ROAD_Y, -36), Vector3(-36, ROAD_Y, -10)
            ]
        "WORKER", "SERVICE":
            return [
                Vector3(-10, ROAD_Y, -10), Vector3(10, ROAD_Y, -10),
                Vector3(10, ROAD_Y, 10), Vector3(-10, ROAD_Y, 10),
                Vector3(-36, ROAD_Y, 10), Vector3(36, ROAD_Y, -10)
            ]
        "RESIDENT":
            return [
                Vector3(-36, ROAD_Y, 36), Vector3(36, ROAD_Y, 36),
                Vector3(-36, ROAD_Y, -36), Vector3(36, ROAD_Y, -36)
            ]
        "COMMUTER", "SHOPPER":
            return [
                Vector3(-58, ROAD_Y, -10), Vector3(58, ROAD_Y, 10),
                Vector3(-10, ROAD_Y, -58), Vector3(10, ROAD_Y, 58),
                Vector3(-36, ROAD_Y, 10), Vector3(36, ROAD_Y, -10)
            ]
        _:
            return [
                Vector3(-10, ROAD_Y, -10), Vector3(10, ROAD_Y, -10),
                Vector3(10, ROAD_Y, 10), Vector3(-10, ROAD_Y, 10),
                Vector3(-36, ROAD_Y, 10), Vector3(36, ROAD_Y, -10)
            ]

func _build_traffic() -> void:
    var traffic_root := Node3D.new()
    traffic_root.name = "LandlyTraffic"
    population_root.add_child(traffic_root)

    var routes := [
        [Vector3(-58, 0.48, 3.0), Vector3(58, 0.48, 3.0)],
        [Vector3(58, 0.48, -3.0), Vector3(-58, 0.48, -3.0)],
        [Vector3(-3.0, 0.48, -58), Vector3(-3.0, 0.48, 58)],
        [Vector3(3.0, 0.48, 58), Vector3(3.0, 0.48, -58)],
        [Vector3(-58, 0.48, 36), Vector3(58, 0.48, 36)]
    ]
    var colors := [
        Color(0.08, 0.18, 0.28), Color(0.22, 0.22, 0.25),
        Color(0.12, 0.30, 0.20), Color(0.32, 0.16, 0.12), Color(0.18, 0.18, 0.22)
    ]

    for i in range(16):
        var route: Array = routes[i % routes.size()]
        var car := Node3D.new()
        car.name = "CityVehicle_%02d" % i
        car.position = route[0]
        traffic_root.add_child(car)
        car.set_meta("traffic_progress", float(i % 8) / 8.0)
        car.set_meta("traffic_speed", 0.032 + float(i % 4) * 0.006)
        car.set_meta("traffic_a", route[0])
        car.set_meta("traffic_b", route[1])
        traffic.append(car)

        _box(car, Vector3(0, 0.42, 0), Vector3(1.65, 0.62, 3.0), colors[i % colors.size()], "VehicleBody")
        _box(car, Vector3(0, 0.82, -0.15), Vector3(1.25, 0.38, 1.45), Color(0.08, 0.13, 0.18), "VehicleCabin")
        for x in [-0.68, 0.68]:
            for z in [-0.9, 0.9]:
                _cylinder(car, Vector3(x, 0.25, z), 0.16, 0.12, Color(0.035, 0.04, 0.05), "Wheel")
        _box(car, Vector3(0, 0.48, -1.53), Vector3(1.2, 0.08, 0.08), Color(0.65, 0.76, 0.82), "HeadLights")

func _process(delta: float) -> void:
    for car in traffic:
        if not is_instance_valid(car):
            continue
        var progress := float(car.get_meta("traffic_progress", 0.0))
        var speed := float(car.get_meta("traffic_speed", 0.045))
        var a: Vector3 = car.get_meta("traffic_a", car.position)
        var b: Vector3 = car.get_meta("traffic_b", car.position)
        progress = fmod(progress + delta * speed, 1.0)
        car.set_meta("traffic_progress", progress)
        car.position = a.lerp(b, progress)
        var direction := b - a
        if direction.length_squared() > 0.01:
            car.rotation.y = atan2(direction.x, direction.z)

func _build_service_zones() -> void:
    _add_sign(Vector3(-44, 3.2, -44), "LANDLY POLICE")
    _add_sign(Vector3(44, 3.2, -44), "LANDLY HOSPITAL")
    _add_sign(Vector3(-44, 3.2, 44), "LANDLY COLLEGE")
    _add_sign(Vector3(44, 3.2, 44), "DEFENCE ZONE")

func _add_sign(position: Vector3, title: String) -> void:
    var sign := Label3D.new()
    sign.text = title
    sign.font_size = 24
    sign.outline_size = 6
    sign.position = position
    sign.modulate = Color(0.55, 0.82, 1.0)
    sign.billboard = BaseMaterial3D.BILLBOARD_ENABLED
    population_root.add_child(sign)

func _cylinder(parent: Node3D, position: Vector3, radius: float, height: float, color: Color, label: String) -> void:
    var mesh := MeshInstance3D.new()
    var shape := CylinderMesh.new()
    shape.top_radius = radius
    shape.bottom_radius = radius
    shape.height = height
    mesh.mesh = shape
    mesh.position = position
    mesh.rotation.z = PI * 0.5
    mesh.material_override = _material(color)
    mesh.name = label
    parent.add_child(mesh)

func _box(parent: Node3D, position: Vector3, size: Vector3, color: Color, label: String) -> void:
    var mesh := MeshInstance3D.new()
    var shape := BoxMesh.new()
    shape.size = size
    mesh.mesh = shape
    mesh.position = position
    mesh.material_override = _material(color)
    mesh.name = label
    parent.add_child(mesh)

func _material(color: Color) -> StandardMaterial3D:
    var material := StandardMaterial3D.new()
    material.albedo_color = color
    material.roughness = 0.68
    return material
